name: 'File Sync'
description: 'Github Action to sync files across repositories'
author: 'kbrashears5'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  REPOSITORIES:
    description: 'Github repositories to sync files to. Optionally provide a branch with @branchName after the repo name. Default is default branch of the repository'
    required: true
  FILES:
    description: 'Files to sync to repositories'
    required: true
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true
  PULL_REQUEST_BRANCH_NAME:
    description: 'Branch name to submit pull request to'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'