name: 'File Sync'
description: 'Github Action to sync files across repositories'
author: 'kbrashears5'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  REPOSITORIES:
    description: 'Github repositories to sync files to. Optionally provide a branch with @branchName after the repo name. Default is master'
    required: true
  FILES:
    description: 'Files to sync to repositories'
    required: true
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true
  PULL_REQUEST:
    description: 'Whether or not to submit a pull request. Only works if branch is not master'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'