name: 'File Sync'
description: 'Github Action to sync files across repositories'
author: 'kbrashears5'
branding:
  icon: 'upload-cloud'
  color: 'purple'
inputs:
  REPOSITORIES:
    description: 'Github repositories to sync files to. Optionally provide a branch with @branchName after the repo name. Default is default branch of the repository'
    required: true
  FILES:
    description: 'Files to sync to repositories'
    required: true
  TOKEN:
    description: 'Personal access token with Repo privileges'
    required: true
  PULL_REQUEST_BRANCH_NAME:
    description: 'Branch name to submit pull request to'
    required: false
    default: ''
  GIT_EMAIL:
    description: 'Email to use for Git'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USERNAME:
    description: 'Username to use for Git'
    required: false
    default: 'github-actions[bot]'

runs:
  using: 'docker'
  image: 'Dockerfile'