name: Repo Metadata Sync

on:
  push:
    branches:
      - main

jobs:
  repo_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@main
      - name: Repo Sync
        uses: kbrashears5/github-action-repo-sync@main
        with:
          TYPE: npm
          PATH: metadata.json
          TOKEN: ${{ secrets.ACTIONS }}